#!/usr/bin/perl -w

# git-helpers-lfw for UNIX-like environments
# Copyright (C) 2012  Lebbeous Fogle-Weekley

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

# Author email: lebbeous@gmail.com

use strict;

my $indent = 1; # maybe make a command line opt later

sub credit_file {
    my $filename = shift;
    my $total = `wc -l $filename | cut -d' ' -f 1`;
    chomp $total;

    my $contributions = `git blame $filename | cut -d'(' -f2 | cut -d' ' -f1-2 | sort | uniq -c | sort -nr `;


    foreach (split(/\n/, $contributions)) {
        /^\s*(\d+)\s*(.+)$/ or next;
        printf("%s%.2f%% %s\n", "\t" x $indent, ($1 / $total) * 100.0, $2);
    }
}

# main
foreach (@ARGV) {
    print "$_\n";
    if (-r) {
        credit_file($_);
    } else {
        print STDERR "$!\n";
    }
}
0;
