#!/bin/bash

# git-helpers-lfw for UNIX-like environments
# Copyright (C) 2012  Lebbeous Fogle-Weekley

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

# Author email: lebbeous@gmail.com

usage() {
    echo "$0 [-f]"
    echo
    echo "If the current branch is set up as a tracking branch, untrack it."
    echo "That is, unset the config values that point to the upstream remote"
    echo "and branch."
    echo
    echo "Options:"
    echo "  -f  Force operation (i.e., don't ask for interactive confirmation)"
    exit 1
}

while getopts "fh" flag; do
    case $flag in
        "f")    FORCE="yes";;
        *) usage;;
    esac
done

branch=`git status | head -1 | cut -d' ' -f4`
if [ -z "$branch" ]; then
	echo "Could not determine branch" 1>&2
	exit 2
fi

remote=`git config --get branch.$branch.remote`
if [ -z "$remote" ]; then
	echo "No remote is set for $branch." >&2
	echo "This is not a tracking branch." >&2
	exit 3
fi

if [ -z "$FORCE" ]; then
    echo "Really delete tracking info for branch '$branch'? " >&2
    read confirm
    if [ "$confirm" != "Y" -a "$confirm" != "y" ]; then
        exit 4
    fi
fi

git config --unset branch.$branch.remote
git config --unset branch.$branch.merge
exit $?
